language: node_js

env:
- PHANTOMJS_BIN=./node_modules/.bin/phantomjs

node_js:
- '6'

script:
  - rm -rf node_modules
  - yarn
  - npm test

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov